version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: financial_sales_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: financial_sales_db
      DB_USER: postgres
      DB_PASSWORD: postgres123
      JWT_SECRET: your_jwt_secret_key_change_in_production
      JWT_EXPIRES_IN: 24h
      NODE_ENV: production
    depends_on:
      - postgres
    command: sh -c "npm run db:init && npm start"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    depends_on:
      - backend

volumes:
  postgres_data: